#!/usr/bin/env bash
#
# Create symlinks from ~ to ~/.config
#

DOTFILES="${DOTFILES:-$HOME/.config}"
SYSTEM_DIR="${SYSTEM_DIR:-$DOTFILES/.system}"
TEMPLATES_DIR="$SYSTEM_DIR/templates"

# Function to process a template with environment variable substitution
process_template() {
  local template="$1"
  local output="$2"

  if [[ ! -f "$template" ]]; then
    echo "  Skipped: $template (not found)"
    return 1
  fi

  mkdir -p "$(dirname "$output")"
  envsubst <"$template" >"$output"
  echo "  Generated: $output"
}

# Function to create symlink safely
create_symlink() {
  local source="$1"
  local target="$2"

  # Skip if source doesn't exist
  if [[ ! -e "$source" ]]; then
    echo "  Skipped: $source (not found)"
    return
  fi

  # If target is already a symlink pointing to the right place, skip
  if [[ -L "$target" ]] && [[ "$(readlink "$target")" == "$source" ]]; then
    echo "  OK: $target"
    return
  fi

  # Remove existing symlink
  if [[ -L "$target" ]]; then
    rm "$target"
  # Backup existing file
  elif [[ -f "$target" ]]; then
    echo "  Backing up: $target -> ${target}.backup"
    mv "$target" "${target}.backup"
  fi

  ln -s "$source" "$target"
  echo "  Created: $target -> $source"
}

# Parse theme flavor for bat theme symlink
THEME_FILE="$SYSTEM_DIR/themes/theme.toml"
if [[ -f "$THEME_FILE" ]]; then
  FLAVOR=$(grep '^flavor *= *"' "$THEME_FILE" | head -1 | sed 's/.*= *"\([^"]*\)".*/\1/')
  CAP_FLAVOR="$(tr '[:lower:]' '[:upper:]' <<<"${FLAVOR:0:1}")${FLAVOR:1}"
fi

echo "Creating symlinks..."

# Git configuration
create_symlink "$DOTFILES/git/config" "$HOME/.gitconfig"

# Hush login (suppress "Last login:" message)
create_symlink "$DOTFILES/fish/hushlogin" "$HOME/.hushlogin"

create_symlink "$DOTFILES/shellcheck/shellcheckrc" "$HOME/.shellcheckrc"

# Global Claude Code instructions (applies to all repos)
# Source lives in 1Password (<Personal Vault> > Private > claude-global-instructions),
# materialized to .system/sensitive/CLAUDE.global.md by secrets.sh.
mkdir -p "$HOME/.claude"
create_symlink "$SYSTEM_DIR/sensitive/CLAUDE.global.md" "$HOME/.claude/CLAUDE.md"

# Global Codex instructions and prompts (applies to all repos)
# CODEX_HOME is set to $HOME/.config/codex in fish/config.fish so that's the
# canonical location; we also link into ~/.codex/ as a fallback for tools
# that read the default path.
mkdir -p "$HOME/.codex"
create_symlink "$DOTFILES/codex/config.toml" "$HOME/.codex/config.toml"
create_symlink "$DOTFILES/codex/hooks.json" "$HOME/.codex/hooks.json"
create_symlink "$DOTFILES/codex/AGENTS.md" "$HOME/.codex/AGENTS.md"
create_symlink "$DOTFILES/codex/prompts" "$HOME/.codex/prompts"

# Sensitive files (if they exist)
create_symlink "$SYSTEM_DIR/sensitive/.npmrc" "$HOME/.npmrc"

# Process templates (non-secret configs that need $HOME expansion)
echo "Processing templates..."
process_template "$TEMPLATES_DIR/glow.yml.tpl" "$DOTFILES/glow/glow.yml"

# macOS app configs (these apps don't respect XDG_CONFIG_HOME)
mkdir -p "$HOME/Library/Preferences/glow"
create_symlink "$DOTFILES/glow/glow.yml" "$HOME/Library/Preferences/glow/glow.yml"

# LaunchAgents directory (plist files generated by secrets.sh)
mkdir -p "$HOME/Library/LaunchAgents"

# Bat syntax theme
# bat 0.25+ auto-discovers .tmTheme files in its config dir; no cache rebuild needed
# (the old `bat cache --build` subcommand was removed).
if [[ -n "${FLAVOR:-}" ]]; then
  mkdir -p "$DOTFILES/bat/themes"
  create_symlink "$SYSTEM_DIR/themes/catppuccin-${FLAVOR}/bat.tmTheme" "$DOTFILES/bat/themes/Catppuccin ${CAP_FLAVOR}.tmTheme"
fi

# Work-specific Claude skills (conditional on hostname)
# Source hostname detection if not already available
if [[ -f "$SYSTEM_DIR/setup/lib/profiles.sh" ]]; then
  source "$SYSTEM_DIR/setup/lib/profiles.sh"
  MACHINE_HOSTNAME="${MACHINE_HOSTNAME:-$(hostname -s)}"
fi

if type -t is_machine_in_group &>/dev/null && is_machine_in_group "$MACHINE_HOSTNAME" "work"; then
  echo "Work machine detected. Linking work-specific Claude skills..."
  WORK_SKILLS_DIR="$SYSTEM_DIR/sensitive/claude-skills"
  if [[ -d "$WORK_SKILLS_DIR" ]]; then
    for skill_dir in "$WORK_SKILLS_DIR"/*/; do
      if [[ -d "$skill_dir" ]]; then
        skill_name=$(basename "$skill_dir")
        create_symlink "$skill_dir" "$DOTFILES/claude/skills/$skill_name"
      fi
    done
  else
    echo "  Work skills directory not found: $WORK_SKILLS_DIR"
    echo "  Run 'secrets' to retrieve skills from 1Password"
  fi

  echo "Linking work-specific Claude rules..."
  WORK_RULES_DIR="$SYSTEM_DIR/sensitive/claude-rules"
  if [[ -d "$WORK_RULES_DIR" ]]; then
    for rule_file in "$WORK_RULES_DIR"/*.md; do
      if [[ -f "$rule_file" ]]; then
        create_symlink "$rule_file" "$DOTFILES/claude/rules/$(basename "$rule_file")"
      fi
    done
  else
    echo "  Work rules directory not found: $WORK_RULES_DIR"
    echo "  Run 'secrets' to retrieve rules from 1Password"
  fi
else
  echo "$MACHINE_HOSTNAME detected, skipping work-specific Claude skills and rules"
fi

echo "Symlinks complete!"
