# =============================================================================
# Media Utilities
# =============================================================================
brew "imagemagick"              # Image manipulation
brew "yt-dlp"                   # Video downloader

# =============================================================================
# Applications (Casks)
# =============================================================================
cask "discord"                  # Chat platform
cask "element"                  # Matrix client
cask "handbrake-app"            # Video encoder
cask "obs"                      # Streaming/recording
cask "proton-mail"              # Encrypted email
cask "signal"                   # E2EE Communication

# =============================================================================
# Mac App Store
# =============================================================================
mas "Final Cut Pro: Create Video", id: 1631624924 # Video editor
mas "Pixelmator Pro: Edit Images", id: 6746662575 # Image editor
