# =============================================================================
# Taps
# =============================================================================
tap "macos-fuse-t/cask", trusted: true

# =============================================================================
# Media Utilities
# =============================================================================
brew "ffmpeg"                         # Audio/video transcoder
brew "imagemagick"                    # Image manipulation
cask "macos-fuse-t/cask/fuse-t"       # FUSE without kernel extensions
cask "macos-fuse-t/cask/fuse-t-sshfs" # Mount remote dirs over SSH
brew "yt-dlp"                         # Video downloader

# =============================================================================
# Applications (Casks)
# =============================================================================
cask "discord"                  # Chat platform
cask "element"                  # Matrix client
cask "handbrake-app"            # Video encoder
cask "obs"                      # Streaming/recording
cask "proton-mail"              # Encrypted email
cask "proton-mail-bridge"       # Email bridge
cask "signal"                   # E2EE Communication
cask "zoom"                     # Video conferencing

# =============================================================================
# Mac App Store
# =============================================================================
mas "Final Cut Pro: Create Video", id: 1631624924 # Video editor
mas "Infuse", id: 1136220934                      # Media player
mas "Parcel", id: 375589283                       # Delivery tracking
mas "Pixelmator Pro: Edit Images", id: 6746662575 # Image editor
mas "Reeder Classic", id: 1529448980              # RSS reader
