#!/bin/bash
# Auto-generated by setup/sync-theme.sh from themes/theme.toml
# Do not edit manually - run setup/sync-theme.sh to regenerate

# Catppuccin Frappe Color Palette
# https://github.com/catppuccin/catppuccin

# Base colors
export BASE=0xff303446
export MANTLE=0xff292c3c
export CRUST=0xff232634

# Surface colors
export SURFACE0=0xff414559
export SURFACE1=0xff51576d
export SURFACE2=0xff626880

# Overlay colors
export OVERLAY0=0xff737994
export OVERLAY1=0xff838ba7
export OVERLAY2=0xff949cbb

# Text colors
export TEXT=0xffc6d0f5
export SUBTEXT0=0xffa5adce
export SUBTEXT1=0xffb5bfe2

# Accent colors
export LAVENDER=0xffbabbf1
export BLUE=0xff8caaee
export SAPPHIRE=0xff85c1dc
export SKY=0xff99d1db
export TEAL=0xff81c8be
export GREEN=0xffa6d189
export YELLOW=0xffe5c890
export PEACH=0xffef9f76
export MAROON=0xffea999c
export RED=0xffe78284
export MAUVE=0xffca9ee6
export PINK=0xfff4b8e4
export FLAMINGO=0xffeebebe
export ROSEWATER=0xfff2d5cf

# Transparent variants (for backgrounds)
export BAR_COLOR=0xcc303446          # 80% opacity base
export ITEM_BG_COLOR=0xe6414559      # 90% opacity surface0
export ACCENT_COLOR=$MAUVE           # Primary accent (mauve/purple)

# Workspace colors
export SPACE_ACTIVE=$LAVENDER        # Active workspace accent (lavender)
export SPACE_INACTIVE=0x66c6d0f5     # 40% opacity text
export SPACE_ACTIVE_BG=0x44babbf1    # 27% opacity lavender

# Front app colors
export FRONT_APP_BG=0x66babbf1       # 40% opacity lavender
export FRONT_APP_BORDER=$LAVENDER    # Lavender border for active app

# Icon colors
export ICON_COLOR=$TEXT
export LABEL_COLOR=$TEXT

# Special status colors
export BATTERY_LOW=$RED
export BATTERY_CHARGING=$GREEN
