# System settings

[set.AppleMultitouchTrackpad]
Clicking = false
TrackpadThreeFingerDrag = false

[set.controlcenter]
BatteryShowPercentage = true
Bluetooth = true

[set.CloudSubscriptionFeatures.optIn]
545129924 = false # Disable Apple Intelligence

[set.dock]
autohide = true
autohide-delay = 0
autohide-time-modifier = 0
expose-group-apps = false
magnification = false
mineffect = "scale"
orientation = "bottom"
show-recents = false
static-only = true
tilesize = 1

[set.finder]
_FXShowPoxisPathInTitle = true
AppleShowAllFiles = true
CreateDesktop = false
FXEnableExtensionChangeWarning = false
FXDefaultSearchScope = "SCcf"
FXRemoveOldTrashItems = true
QuitMenuItem = true
ShowExternalHardDrivesOnDesktop = false
ShowPathbar = true

[set.HIToolBox]
AppleFnUsageType = 0

[set.LaunchServices]
LSQuarantine = false

[set.menuextra.clock]
FlashDateSeparators = false
DateFormat = "\"EEE d MMM HH:mm\""
Show24Hour = true
ShowAMPM = false
ShowDate = 1
ShowDayOfWeek = true
ShowSeconds = false

[set.NSGlobalDomain]
# iCloud
NSDocumentSaveNewDocumentsToCloud = false

# Finder
NSNavPanelExpandedStateForSaveMode = true
NSNavPanelExpandedStateForSaveMode2 = true
NSTableViewDefaultSizeMode = 1

# Mouse
ApplePressAndHoldEnabled = true
CGDisableCursorLocationMagnification = true

# Navigation
AppleEnableSwipeNavigateWithScrolls = false
AppleMiniaturizeOnDoubleClick = true

# Sound
"com.apple.sound.beep.volume" = 0
"com.apple.sound.beep.feedback" = 0

# Spellcheck
NSAutomaticCapitalizationEnabled = false
NSAutomaticDashSubstitutionEnabled = false
NSAutomaticPeriodSubstitutionEnabled = false
NSAutomaticQuoteSubstitutionEnabled = false
NSAutomaticSpellingCorrectionEnabled = false

# System
AppleShowAllExtensions = false
AppleShowAllFiles = true
NSDisableAutomaticTermination = false

# UI
_HIHideMenuBar = true

[set.NSGlobalDomain.com.apple.keyboard]
fnState = false

[set.screencapture]
disable-shadow = true
show-thumbnail = false
target = "clipboard"
type = "png"

# External command execution
# This includes setting the global hostname and configuring sudo authentication with Touch ID.

[vars]
hostname = "athena"

[commands.darkmode]
run = "osascript -e 'tell application \"System Events\" to tell appearance preferences to set dark mode to true'"

[commands.dns]
run = "networksetup -setdnsservers 'Wi-Fi' '94.140.14.14' '94.140.15.15' && networksetup -setdnsservers 'Thunderbolt Ethernet Slot 1' '94.140.14.14' '94.140.15.15'"

[commands.hostname]
run = "scutil --set ComputerName $hostname && scutil --set HostName $hostname && scutil --set LocalHostName $hostname"
sudo = true

[commands.screenshot]
run = "defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 31 \"{enabled = 0; value = { parameters = (119, 13, 1310720); type = 'standard'; }; }\" && defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 31 \"{enabled = 1; value = { parameters = (119, 13, 1310720); type = 'standard'; }; }\""

[commands.sleep]
run = "pmset -a sleep 30 && pmset -a displaysleep 15"
sudo = true

[commands.touchid]
run = "sed -e 's/^#auth/auth/' /etc/pam.d/sudo_local.template | tee /etc/pam.d/sudo_local"
sudo = true

[commands.wall]
run = "osascript -e 'tell application \"System Events\" to tell every desktop to set picture to \"~/.local/share/chezmoi/assets/wallpapers/comfy-home.png\" as POSIX file'"

# Homebrew formulae/casks list
# Please see: https://github.com/hitblast/cutler/blob/main/examples/brew.toml

# TODO: Fonts
